const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => document.querySelectorAll(selector);

const defaultData = {
  tasks: [{ text: 'Review biology chapter 4', tag: 'Biology', done: false }],
  classes: [{ id: 'biology', name: 'Biology', teacher: 'Dr. Morgan', color: '#8b7cf6', assignments: [] }],
  notes: [],
  flashcards: [],
  messages: []
};

let data;
try { data = JSON.parse(localStorage.getItem('bloomData')) || defaultData; } catch { data = defaultData; }
data.classes = Array.isArray(data.classes) ? data.classes : [];
data.classes.forEach(c => c.assignments = Array.isArray(c.assignments) ? c.assignments : []);
data.tasks = Array.isArray(data.tasks) ? data.tasks : [];
data.notes = Array.isArray(data.notes) ? data.notes : [];
data.flashcards = Array.isArray(data.flashcards) ? data.flashcards : (data.flashcardSets || []);
data.messages = Array.isArray(data.messages) ? data.messages : [];

let currentPage = 'dashboard';
let calendarMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);
let timer = null;
let timerSeconds = 1500;

function save() { localStorage.setItem('bloomData', JSON.stringify(data)); }
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#039;' }[char])); }
function toast(message) { const el = $('#toast'); if (!el) return; el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2200); }
function openModal(content) { $('#modalContent').innerHTML = content; $('#modal').classList.remove('hidden'); }
function closeModal() { $('#modal').classList.add('hidden'); }
function uid(prefix) { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; }
function dateKey(date) { return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`; }
function allAssignments() { return data.classes.flatMap(c => c.assignments.map(a => ({ ...a, className: c.name, classColor: c.color, classId: c.id }))); }

function dashboard() {
  const completed = data.tasks.filter(t => t.done).length;
  const percent = data.tasks.length ? Math.round(completed / data.tasks.length * 100) : 0;
  return `<div class="grid two"><div class="card welcome"><span class="eyebrow">WELCOME BACK</span><h2>Small steps, big progress.</h2><p>Keep your goals gentle and your focus clear.</p><div class="plant">🌱</div></div><div class="card"><div class="section-title"><h3>Progress</h3><span class="pill purple">${percent}%</span></div><div class="progress-bar"><i style="width:${percent}%"></i></div><p class="muted">${completed} of ${data.tasks.length} tasks complete.</p></div></div><div class="grid three" style="margin-top:18px"><div class="card stat"><div class="stat-icon mint">✓</div><div><b>${completed}</b><small>Tasks done</small></div></div><div class="card stat"><div class="stat-icon blue">▤</div><div><b>${allAssignments().length}</b><small>Assignments</small></div></div><div class="card stat"><div class="stat-icon yellow">♧</div><div><b>${data.classes.length}</b><small>Classes</small></div></div></div><div class="grid two" style="margin-top:18px"><div class="card"><div class="section-title"><h3>My tasks</h3><button class="link-btn" data-action="task">+ Add task</button></div>${data.tasks.map((t,i)=>`<label class="task ${t.done?'done':''}"><input type="checkbox" data-task="${i}" ${t.done?'checked':''}><span>${esc(t.text)}</span><small>${esc(t.tag)}</small></label>`).join('') || '<div class="empty">No tasks yet.</div>'}</div><div class="card"><div class="section-title"><h3>Study timer</h3><span class="pill green">Focus</span></div><div class="timer-box"><div id="timerDisplay" class="timer-display">${formatTime()}</div><button class="primary wide" data-action="timer">${timer?'Pause':'Start timer'}</button></div></div></div>`;
}
function formatTime() { return `${String(Math.floor(timerSeconds/60)).padStart(2,'0')}:${String(timerSeconds%60).padStart(2,'0')}`; }
function calendar() {
  const y=calendarMonth.getFullYear(), m=calendarMonth.getMonth(), first=new Date(y,m,1).getDay(), total=new Date(y,m+1,0).getDate(), label=calendarMonth.toLocaleString('en-US',{month:'long',year:'numeric'}), assignments=allAssignments(); let cells='';
  for(let i=0;i<first;i++) cells += '<div class="calendar-empty"></div>';
  for(let day=1;day<=total;day++){const key=dateKey(new Date(y,m,day));const items=assignments.filter(a=>a.dueDate===key);cells += `<div class="calendar-day ${key===dateKey(new Date())?'today':''}"><b>${day}</b><button class="day-add" data-add-date="${key}">+</button>${items.map(a=>`<span class="calendar-event" style="background:${a.classColor||'var(--primary)'}">${esc(a.title)}<small>${esc(a.className)}</small></span>`).join('')}</div>`;}
  return `<div class="page-head"><h2>Calendar</h2><button class="primary" data-add-date="${dateKey(new Date())}">+ Add assignment</button></div><div class="calendar-wrap"><div class="card"><div class="calendar-header"><button class="btn" data-action="prev">‹</button><h2>${label}</h2><button class="btn" data-action="next">›</button></div><div class="calendar-grid"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span>${cells}</div></div><div class="card"><div class="section-title"><h3>Upcoming</h3></div>${assignments.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).map(a=>`<div class="task"><span>${esc(a.title)}</span><small>${esc(a.className)} · ${a.dueDate}</small></div>`).join('')||'<div class="empty">No assignments yet.</div>'}</div></div>`;
}
function classes() { return `<div class="page-head"><h2>My classes</h2><button class="primary" data-action="class">+ New class</button></div><div class="grid three">${data.classes.map(c=>`<div class="card class-card" style="border-left-color:${c.color}"><h3>${esc(c.name)}</h3><p>${esc(c.teacher)}</p><p class="muted">${c.assignments.length} assignments</p><button class="primary wide" data-add-class="${c.id}">+ Assignment</button></div>`).join('')||'<div class="empty">No classes yet.</div>'}</div>`; }
function flashcards() { return `<div class="page-head"><h2>Flashcards</h2><button class="primary" data-action="flashcards">+ New set</button></div><div class="grid three">${data.flashcards.map((d,i)=>`<div class="card"><div class="section-title"><h3>${esc(d.name)}</h3><span class="pill purple">${(d.cards||[]).length}</span></div><p class="muted">Saved flashcard group</p><button class="primary wide" data-study="${i}">Study set</button></div>`).join('')||'<div class="empty">No flashcard sets yet.</div>'}</div>`; }
function notes() { return `<div class="page-head"><h2>Notes</h2><button class="primary" data-action="note">+ New note</button></div><div class="notes-list">${data.notes.map((n,i)=>`<div class="card note-card"><h3>${esc(n.title)}</h3><p>${esc(n.body)}</p><button class="link-btn" data-delete-note="${i}">Delete</button></div>`).join('')||'<div class="empty">No notes yet.</div>'}</div>`; }
function inbox() { return `<div class="page-head"><h2>Inbox</h2><button class="primary" data-action="message">+ New message</button></div><div class="card">${data.messages.map(m=>`<div class="message"><div class="avatar">${esc(m.from[0])}</div><div><b>${esc(m.from)}</b><p>${esc(m.body)}</p></div></div>`).join('')||'<div class="empty">No messages yet.</div>'}</div>`; }
function render() { const views={dashboard,calendar,classes,flashcards,notes,inbox}; $('#pageContent').innerHTML=views[currentPage](); $('#pageTitle').textContent={dashboard:'Good morning, Hailey ✦',calendar:'Your calendar',classes:'My classes',flashcards:'Flashcards',notes:'Your notes',inbox:'Inbox'}[currentPage]; $$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.page===currentPage)); bind(); }

function assignmentForm(date, classId) { openModal(`<h2>Add assignment</h2><form id="assignmentForm"><label>Class<select name="classId" required>${data.classes.map(c=>`<option value="${c.id}" ${c.id===classId?'selected':''}>${esc(c.name)}</option>`).join('')}</select></label><label>Title<input name="title" required placeholder="Read Chapter 5"></label><label>Due date<input type="date" name="dueDate" value="${date||dateKey(new Date())}" required></label><label>Type<select name="type"><option>Assignment</option><option>Homework</option><option>Quiz</option><option>Project</option></select></label><button class="primary wide">Add to calendar</button></form>`); $('#assignmentForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const c=data.classes.find(x=>x.id===v.classId);c.assignments.push({id:uid('a'),title:v.title,dueDate:v.dueDate,type:v.type});save();closeModal();render();toast('Assignment added!');}; }
function bind() { $$('[data-page]').forEach(b=>b.onclick=()=>{currentPage=b.dataset.page;render();}); $$('[data-task]').forEach(x=>x.onchange=()=>{data.tasks[x.dataset.task].done=x.checked;save();render();}); $$('[data-add-date]').forEach(b=>b.onclick=()=>assignmentForm(b.dataset.addDate)); $$('[data-add-class]').forEach(b=>b.onclick=()=>assignmentForm(dateKey(new Date()),b.dataset.addClass)); $$('[data-delete-note]').forEach(b=>b.onclick=()=>{data.notes.splice(Number(b.dataset.deleteNote),1);save();render();}); $$('[data-study]').forEach(b=>study(data.flashcards[Number(b.dataset.study)])); $$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action)); }
function action(type) { if(type==='prev'){calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()-1,1);render();} if(type==='next'){calendarMonth=new Date(calendarMonth.getFullYear(),calendarMonth.getMonth()+1,1);render();} if(type==='timer'){if(timer){clearInterval(timer);timer=null;}else timer=setInterval(()=>{if(timerSeconds>0)timerSeconds--;if($('#timerDisplay'))$('#timerDisplay').textContent=formatTime();},1000);render();} if(type==='class')openModal(`<h2>New class</h2><form id="classForm"><label>Name<input name="name" required></label><label>Teacher<input name="teacher"></label><button class="primary wide">Create class</button></form>`),$('#classForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));data.classes.push({id:uid('c'),name:v.name,teacher:v.teacher||'Teacher',color:'#8b7cf6',assignments:[]});save();closeModal();render();}; if(type==='task')openModal(`<h2>Add task</h2><form id="taskForm"><label>Task<input name="text" required></label><label>Class<input name="tag"></label><button class="primary wide">Add task</button></form>`),$('#taskForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));data.tasks.push({text:v.text,tag:v.tag||'General',done:false});save();closeModal();render();}; if(type==='note')openModal(`<h2>New note</h2><form id="noteForm"><label>Title<input name="title" required></label><label>Note<textarea name="body" required></textarea></label><button class="primary wide">Save note</button></form>`),$('#noteForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));data.notes.push(v);save();closeModal();render();}; if(type==='message')openModal(`<h2>New message</h2><form id="messageForm"><label>To<input name="from" required></label><label>Message<textarea name="body" required></textarea></label><button class="primary wide">Send</button></form>`),$('#messageForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));data.messages.unshift(v);save();closeModal();render();}; if(type==='flashcards')openModal(`<h2>New flashcard set</h2><form id="deckForm"><label>Set title<input name="name" required></label><label>Cards, one per line: question :: answer<textarea name="cards"></textarea></label><button class="primary wide">Save set</button></form>`),$('#deckForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));data.flashcards.push({name:v.name,cards:v.cards.split('\n').filter(Boolean).map(line=>{const p=line.split('::');return {front:p[0].trim(),back:(p.slice(1).join('::')||'').trim()};})});save();closeModal();render();}; }
function study(deck){let i=0,back=false;const show=()=>{const c=deck.cards[i];openModal(`<h2>${esc(deck.name)}</h2><div class="flashcard"><b>${esc(back?c.back:c.front)}</b><small>Click flip to see the ${back?'question':'answer'}</small></div><div class="card-actions"><button class="btn" id="flip">Flip</button><button class="primary" id="next">Next</button></div>`);$('#flip').onclick=()=>{back=!back;show();};$('#next').onclick=()=>{i=(i+1)%deck.cards.length;back=false;show();};}; if(deck.cards.length)show(); }

$('#closeModal').onclick=closeModal; $('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();}; $('#quickAdd').onclick=()=>{currentPage='calendar';render();};
if($('#logoutBtn')) $('#logoutBtn').onclick=()=>{localStorage.removeItem('bloomUser');location.reload();};
render();
