/* Study Bloom interaction enhancements: real current-month calendar, day add buttons, and card editor */
(function () {
  const extraCss = `
    .calendar-toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:18px}.calendar-toolbar h2{font:600 22px Fredoka;margin:0}.calendar-day{min-height:112px;border:1px solid var(--line);border-radius:12px;padding:9px;background:var(--surface);position:relative}.calendar-day:hover{border-color:var(--primary)}.calendar-day.today{box-shadow:inset 0 0 0 2px var(--primary);background:#faf8ff}.calendar-empty{min-height:112px;border:1px dashed var(--line);border-radius:12px;opacity:.4}.day-number{font-weight:700}.day-add{position:absolute;right:7px;top:5px;background:transparent;color:var(--primary);font-size:18px;line-height:1}.day-events{display:grid;gap:5px;margin-top:8px}.calendar-event{display:block;color:#fff;border-radius:6px;padding:5px 6px;font-size:10px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.calendar-event small{display:block;opacity:.85}.calendar-grid{grid-template-columns:repeat(7,minmax(0,1fr))}.flashcard-editor{display:grid;gap:18px}.editor-card{border:1px solid var(--line);border-radius:22px;padding:28px;min-height:290px;display:grid;place-items:center;position:relative;background:linear-gradient(135deg,var(--surface),#f4efff)}.editor-card textarea{width:min(520px,90%);min-height:145px;text-align:center;font-size:20px;border:2px dashed var(--primary);background:#ffffffaa}.corner{position:absolute;color:var(--primary);font-size:24px}.corner.tl{top:16px;left:18px}.corner.tr{top:16px;right:18px}.corner.bl{bottom:16px;left:18px}.corner.br{bottom:16px;right:18px}.lined-card{background:repeating-linear-gradient(to bottom,var(--surface) 0,var(--surface) 31px,var(--line) 32px);display:block;padding:26px 34px}.lined-card textarea{width:100%;min-height:220px;border:0;background:transparent;resize:vertical;line-height:32px;padding:0;font-size:16px}.card-row{display:grid;gap:12px;padding:16px 0;border-bottom:1px solid var(--line)}.card-row:last-child{border-bottom:0}.card-row-head{display:flex;justify-content:space-between;align-items:center}.danger{color:#c05b75!important}.calendar-help{color:var(--muted);font-size:12px;margin:0 0 12px}@media(max-width:700px){.calendar-day,.calendar-empty{min-height:76px}.calendar-event{font-size:8px;padding:3px}.day-add{font-size:14px}}
  `;
  const style = document.createElement('style'); style.textContent = extraCss; document.head.appendChild(style);

  function iso(y,m,d){return `${y}-${String(m+1).padStart(2,'0')}-${String(d).padStart(2,'0')}`;}
  function todayKey(){const d=new Date();return iso(d.getFullYear(),d.getMonth(),d.getDate());}
  function assignRows(){return state.classes.flatMap(cls=>(cls.assignments||[]).map(a=>({...a,classId:cls.id,className:cls.name,classColor:cls.color})));}
  function addAssignmentModal(date, classId){
    const options=state.classes.map(c=>`<option value="${c.id}" ${c.id===classId?'selected':''}>${escapeHtml(c.name)}</option>`).join('');
    openModal(`<h2>Add assignment</h2><p class="calendar-help">It will appear on the selected day and under its class.</p><form id="enhancedAssignmentForm" class="sheet-form"><label>Class<select name="classId" required>${options}</select></label><label>Title<input name="title" required placeholder="Read Chapter 5"></label><label>Type<select name="type"><option>Assignment</option><option>Homework</option><option>Quiz</option><option>Project</option><option>Reading</option><option>Practice</option></select></label><label>Due date<input type="date" name="dueDate" value="${date||todayKey()}" required></label><label>Notes<textarea name="notes" placeholder="Optional details"></textarea></label><button class="primary wide">Add to calendar</button></form>`);
    $('#enhancedAssignmentForm').onsubmit=e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.target));const c=state.classes.find(x=>x.id===v.classId);if(!c)return;c.assignments=c.assignments||[];c.assignments.push({id:'assignment-'+Date.now(),title:v.title,type:v.type,dueDate:v.dueDate,notes:v.notes||''});saveState();closeModal();renderPage();showToast('Assignment added to the calendar.');};
  }
  renderCalendar=function(){
    const y=currentCalendarMonth.getFullYear(),m=currentCalendarMonth.getMonth(),label=currentCalendarMonth.toLocaleString('en-US',{month:'long',year:'numeric'}),first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(),rows=assignRows();let cells='';
    for(let i=0;i<first;i++)cells+='<div class="calendar-empty"></div>';
    for(let d=1;d<=days;d++){const key=iso(y,m,d), items=rows.filter(a=>a.dueDate===key), isToday=key===todayKey();cells+=`<div class="calendar-day ${isToday?'today':''}"><div class="day-number">${d}</div><button class="day-add" data-enhanced-add="${key}" title="Add assignment on ${key}">+</button><div class="day-events">${items.map(a=>`<span class="calendar-event" style="background:${a.classColor||'var(--primary)'}" title="${escapeHtml(a.notes||'')}">${escapeHtml(a.title)}<small>${escapeHtml(a.className)}</small></span>`).join('')}</div></div>`;}
    const upcoming=rows.sort((a,b)=>a.dueDate.localeCompare(b.dueDate)).slice(0,8).map(a=>`<div class="mini-assignment" style="border-left:4px solid ${a.classColor||'var(--primary)'}"><strong>${escapeHtml(a.title)}</strong><span>${escapeHtml(a.className)} • ${escapeHtml(a.type)}</span><small>${new Date(a.dueDate+'T00:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}</small></div>`).join('')||'<div class="empty">No assignments yet. Use + on any day.</div>';
    return `<div class="page-head"><h2>Calendar</h2><button class="primary" data-enhanced-add="${todayKey()}">+ Add assignment</button></div><div class="calendar-wrap"><div class="card"><div class="calendar-toolbar"><button class="soft-btn" data-action="prevMonth">←</button><h2>${label}</h2><button class="soft-btn" data-action="nextMonth">→</button></div><p class="calendar-help">Current month • click the + on a day to add an assignment there.</p><div class="calendar-grid"><span>Sun</span><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span>${cells}</div></div><div class="card"><div class="section-title"><h3>Upcoming assignments</h3><span class="pill purple">${rows.length}</span></div>${upcoming}</div></div>`;
  };

  function openDeckEditor(deck){
    let cards=(deck?.cards||[]).map(c=>({front:c.front||'',back:c.back||''}));if(!cards.length)cards=[{front:'',back:''}];
    const render=()=>{openModal(`<div class="flashcard-editor"><div class="section-title"><h2>${deck?'Edit':'New'} flashcard set</h2><span class="pill purple">${cards.length} cards</span></div><label>Set title<input id="deckTitle" value="${escapeHtml(deck?.name||'')}" placeholder="Biology review"></label><div id="editorCards">${cards.map((c,i)=>`<div class="card-row"><div class="card-row-head"><strong>Card ${i+1}</strong><button class="link-btn danger" data-remove-card="${i}">Remove</button></div><div class="editor-card"><span class="corner tl">✦</span><span class="corner tr">✦</span><span class="corner bl">✦</span><span class="corner br">✦</span><textarea data-front="${i}" placeholder="Type the question or prompt...">${escapeHtml(c.front)}</textarea></div><div class="editor-card lined-card"><textarea data-back="${i}" placeholder="Write the answer on the lines...">${escapeHtml(c.back)}</textarea></div></div>`).join('')}</div><div class="card-actions"><button class="btn" id="addAnotherCard">+ Add card</button><button class="primary" id="saveDeck">Save set</button></div></div>`);$$('[data-remove-card]').forEach(b=>b.onclick=()=>{cards.splice(Number(b.dataset.removeCard),1);if(!cards.length)cards.push({front:'',back:''});render();});$('#addAnotherCard').onclick=()=>{cards.push({front:'',back:''});render();};$('#saveDeck').onclick=()=>{const title=$('#deckTitle').value.trim();if(!title){showToast('Give your set a title first.');return;}$$('[data-front]').forEach(x=>cards[Number(x.dataset.front)].front=x.value);$$('[data-back]').forEach(x=>cards[Number(x.dataset.back)].back=x.value);cards=cards.filter(c=>c.front.trim()||c.back.trim());if(!cards.length){showToast('Add at least one card.');return;}if(deck){deck.name=title;deck.cards=cards;}else state.flashcardSets.push({id:'deck-'+Date.now(),name:title,cards});saveState();closeModal();renderPage();showToast('Flashcard set saved.');};};
    render();
  }
  function flashcardAction(button){const deck=state.flashcardSets.find(d=>d.id===button.dataset.deckId);if(deck)openDeckEditor(deck);}
  const oldHandleAction=handleAction;
  handleAction=function(e){const b=e.currentTarget;if(b.dataset.enhancedAdd){addAssignmentModal(b.dataset.enhancedAdd);return;}if(b.dataset.action==='addFlashcardSet'){openDeckEditor(null);return;}if(b.dataset.action==='editFlashcardSet'){flashcardAction(b);return;}oldHandleAction(e);};
  const oldRenderFlashcards=renderFlashcards;
  renderFlashcards=function(){return `<div class="page-head"><h2>Flashcard sets</h2><button class="primary" data-action="addFlashcardSet">+ New set</button></div><div class="grid three">${state.flashcardSets.map(d=>`<div class="card deck-card"><div class="section-title"><h3>${escapeHtml(d.name)}</h3><span class="pill purple">${d.cards.length} cards</span></div><p class="muted">Rounded cards with a prompt front and lined answer back.</p><div class="card-actions"><button class="primary" data-action="studyDeck" data-deck-id="${d.id}">Study</button><button class="btn" data-action="editFlashcardSet" data-deck-id="${d.id}">Edit</button></div></div>`).join('')||'<div class="empty">No sets yet.</div>'}</div>`;};
  const content=$('#pageContent');content.addEventListener('click',e=>{const b=e.target.closest('[data-enhanced-add]');if(b){e.preventDefault();e.stopImmediatePropagation();addAssignmentModal(b.dataset.enhancedAdd);}},true);
  const oldRenderPage=renderPage;renderPage=function(){oldRenderPage();if(currentPage==='calendar'){$$('[data-enhanced-add]').forEach(b=>b.onclick=e=>{e.preventDefault();addAssignmentModal(b.dataset.enhancedAdd);});}};
  $('#quickAdd').onclick=()=>{currentPage='calendar';renderPage();setTimeout(()=>addAssignmentModal(todayKey()),0);};
  renderPage();
})();
